version: 3

components:
  consts:           { in: internal/core/consts/** }
  models:           { in: internal/core/models/** }
  ports:            { in: internal/core/ports/** }
  drivers:          { in: internal/adapters/drivers/** }
  drivens:          { in: internal/adapters/drivens/** }
  implementations:  { in: internal/kycservices } # customizable to each case
  api:              { in: cmd/api/** }
  mocks:            { in: mocks/** }
  fixture:          { in: internal/fixture/** }
  internal:         { in: internal }

vendors:
  assert: { in: github.com/stretchr/testify/assert }
  mock:   { in: github.com/stretchr/testify/mock }
  uuid:   { in: github.com/google/uuid  }
  chi:
    in:
      - github.com/go-chi/chi/v5
      - github.com/go-chi/chi/v5/middleware

commonComponents:
  - consts
  - models
  - mocks
  - fixture

commonVendors:
  - uuid

deps:
  models:
    mayDependOn:
      - consts

  ports:
    mayDependOn:
      - consts

  drivers:
    mayDependOn:
      - ports
      - drivens
      - implementations

  drivens:
    mayDependOn:
      - ports

  implementations:
    mayDependOn:
      - ports
      - drivers
      - drivens
      - implementations
    canUse:
      - assert

  api:
    mayDependOn:
      - ports
      - implementations
      - drivers
      - drivens
    canUse:
      - chi

  mocks:
    canUse:
      - mock