// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// HTTPHandler is an autogenerated mock type for the HTTPHandler type
type HTTPHandler struct {
	mock.Mock
}

type HTTPHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *HTTPHandler) EXPECT() *HTTPHandler_Expecter {
	return &HTTPHandler_Expecter{mock: &_m.Mock}
}

// Func provides a mock function with given fields: w, r
func (_m *HTTPHandler) Func(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// HTTPHandler_Func_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Func'
type HTTPHandler_Func_Call struct {
	*mock.Call
}

// Func is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *HTTPHandler_Expecter) Func(w interface{}, r interface{}) *HTTPHandler_Func_Call {
	return &HTTPHandler_Func_Call{Call: _e.mock.On("Func", w, r)}
}

func (_c *HTTPHandler_Func_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *HTTPHandler_Func_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *HTTPHandler_Func_Call) Return() *HTTPHandler_Func_Call {
	_c.Call.Return()
	return _c
}

func (_c *HTTPHandler_Func_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *HTTPHandler_Func_Call {
	_c.Call.Return(run)
	return _c
}

// Method provides a mock function with given fields:
func (_m *HTTPHandler) Method() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Method")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// HTTPHandler_Method_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Method'
type HTTPHandler_Method_Call struct {
	*mock.Call
}

// Method is a helper method to define mock.On call
func (_e *HTTPHandler_Expecter) Method() *HTTPHandler_Method_Call {
	return &HTTPHandler_Method_Call{Call: _e.mock.On("Method")}
}

func (_c *HTTPHandler_Method_Call) Run(run func()) *HTTPHandler_Method_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HTTPHandler_Method_Call) Return(_a0 string) *HTTPHandler_Method_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HTTPHandler_Method_Call) RunAndReturn(run func() string) *HTTPHandler_Method_Call {
	_c.Call.Return(run)
	return _c
}

// Pattern provides a mock function with given fields:
func (_m *HTTPHandler) Pattern() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pattern")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// HTTPHandler_Pattern_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pattern'
type HTTPHandler_Pattern_Call struct {
	*mock.Call
}

// Pattern is a helper method to define mock.On call
func (_e *HTTPHandler_Expecter) Pattern() *HTTPHandler_Pattern_Call {
	return &HTTPHandler_Pattern_Call{Call: _e.mock.On("Pattern")}
}

func (_c *HTTPHandler_Pattern_Call) Run(run func()) *HTTPHandler_Pattern_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HTTPHandler_Pattern_Call) Return(_a0 string) *HTTPHandler_Pattern_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HTTPHandler_Pattern_Call) RunAndReturn(run func() string) *HTTPHandler_Pattern_Call {
	_c.Call.Return(run)
	return _c
}

// NewHTTPHandler creates a new instance of HTTPHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPHandler(t interface {
	mock.TestingT
	Cleanup(func())
},
) *HTTPHandler {
	mock := &HTTPHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
