// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/johnfercher/go-hexagonal/internal/core/models"
	mock "github.com/stretchr/testify/mock"

	userstatus "github.com/johnfercher/go-hexagonal/internal/core/consts/userstatus"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// CreatePending provides a mock function with given fields: ctx, creation
func (_m *UserRepository) CreatePending(ctx context.Context, creation *models.UserCreation) (string, error) {
	ret := _m.Called(ctx, creation)

	if len(ret) == 0 {
		panic("no return value specified for CreatePending")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserCreation) (string, error)); ok {
		return rf(ctx, creation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserCreation) string); ok {
		r0 = rf(ctx, creation)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UserCreation) error); ok {
		r1 = rf(ctx, creation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_CreatePending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePending'
type UserRepository_CreatePending_Call struct {
	*mock.Call
}

// CreatePending is a helper method to define mock.On call
//   - ctx context.Context
//   - creation *models.UserCreation
func (_e *UserRepository_Expecter) CreatePending(ctx interface{}, creation interface{}) *UserRepository_CreatePending_Call {
	return &UserRepository_CreatePending_Call{Call: _e.mock.On("CreatePending", ctx, creation)}
}

func (_c *UserRepository_CreatePending_Call) Run(run func(ctx context.Context, creation *models.UserCreation)) *UserRepository_CreatePending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UserCreation))
	})
	return _c
}

func (_c *UserRepository_CreatePending_Call) Return(_a0 string, _a1 error) *UserRepository_CreatePending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_CreatePending_Call) RunAndReturn(run func(context.Context, *models.UserCreation) (string, error)) *UserRepository_CreatePending_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, m
func (_m *UserRepository) UpdateStatus(ctx context.Context, id string, status userstatus.Status, m map[string]string) error {
	ret := _m.Called(ctx, id, status, m)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, userstatus.Status, map[string]string) error); ok {
		r0 = rf(ctx, id, status, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type UserRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status userstatus.Status
//   - m map[string]string
func (_e *UserRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, m interface{}) *UserRepository_UpdateStatus_Call {
	return &UserRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, m)}
}

func (_c *UserRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status userstatus.Status, m map[string]string)) *UserRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(userstatus.Status), args[3].(map[string]string))
	})
	return _c
}

func (_c *UserRepository_UpdateStatus_Call) Return(_a0 error) *UserRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, string, userstatus.Status, map[string]string) error) *UserRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
},
) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
